version: '3'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: "python app.py"
  
  worker:
    build: .
    depends_on:
      - redis
    command: "python worker.py"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: